# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\Brendan\Documents\CS 361\MTBApp\GUI\Home_screen.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_HomeWindow(object):
    def setupUi(self, HomeWindow):
        HomeWindow.setObjectName("HomeWindow")
        HomeWindow.resize(798, 603)
        self.centralwidget = QtWidgets.QWidget(HomeWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.title = QtWidgets.QLabel(self.centralwidget)
        self.title.setGeometry(QtCore.QRect(220, 0, 381, 81))
        font = QtGui.QFont()
        font.setFamily("Rockwell Condensed")
        font.setPointSize(26)
        self.title.setFont(font)
        self.title.setObjectName("title")
        self.GenerateTrail = QtWidgets.QPushButton(self.centralwidget)
        self.GenerateTrail.setGeometry(QtCore.QRect(310, 120, 141, 61))
        font = QtGui.QFont()
        font.setFamily("Rockwell Condensed")
        font.setPointSize(14)
        self.GenerateTrail.setFont(font)
        self.GenerateTrail.setObjectName("GenerateTrail")
        self.reviewTrail = QtWidgets.QPushButton(self.centralwidget)
        self.reviewTrail.setGeometry(QtCore.QRect(310, 250, 141, 61))
        font = QtGui.QFont()
        font.setFamily("Rockwell Condensed")
        font.setPointSize(14)
        self.reviewTrail.setFont(font)
        self.reviewTrail.setObjectName("reviewTrail")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(310, 180, 141, 21))
        font = QtGui.QFont()
        font.setFamily("Rockwell Condensed")
        font.setPointSize(12)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(310, 310, 141, 21))
        font = QtGui.QFont()
        font.setFamily("Rockwell Condensed")
        font.setPointSize(12)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(0, 560, 111, 31))
        font = QtGui.QFont()
        font.setFamily("Rockwell Condensed")
        font.setPointSize(8)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        HomeWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(HomeWindow)
        self.statusbar.setObjectName("statusbar")
        HomeWindow.setStatusBar(self.statusbar)

        self.retranslateUi(HomeWindow)
        QtCore.QMetaObject.connectSlotsByName(HomeWindow)

    def retranslateUi(self, HomeWindow):
        _translate = QtCore.QCoreApplication.translate
        HomeWindow.setWindowTitle(_translate("HomeWindow", "MainWindow"))
        self.title.setText(_translate("HomeWindow", "Mountain Bike Trail Generator"))
        self.GenerateTrail.setText(_translate("HomeWindow", "Generate Trail"))
        self.reviewTrail.setText(_translate("HomeWindow", "Review Trail"))
        self.label_2.setText(_translate("HomeWindow", "Click to go to trail search"))
        self.label_3.setText(_translate("HomeWindow", "Click to go to trail review"))
        self.label_4.setText(_translate("HomeWindow", "Application by Brendan Cook"))
